# Generated by Django 5.2.3 on 2025-07-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="education",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
