# Generated by Django 5.2.4 on 2025-07-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_userprofile_education_userprofile_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
    ]
